--- #YAML:1.0
name: Term-ReadLine-Zoid
version: 0.07
author:
  - Jaap Karssenberg <pardus@cpan.org>
abstract: another ReadLine package
license: perl
requires:
  AutoLoader: 0
  Term::ReadKey: 0
recommends:
  File::Temp: 0
build_requires:
  AutoSplit: 0
provides:
  Term::ReadLine::Bender:
    file: lib/Term/ReadLine/Bender.pm
    version: 0.07
  Term::ReadLine::Bender::Base:
    file: lib/Term/ReadLine/Bender/Base.pm
    version: 0.06
  Term::ReadLine::Bender::Emacs:
    file: lib/Term/ReadLine/Bender/Emacs.pm
    version: 0.01
  Term::ReadLine::Bender::FileBrowse:
    file: lib/Term/ReadLine/Bender/FileBrowse.pm
    version: 0.01
  Term::ReadLine::Bender::ISearch:
    file: lib/Term/ReadLine/Bender/ISearch.pm
    version: 0.06
  Term::ReadLine::Bender::ViCommand:
    file: lib/Term/ReadLine/Bender/ViCommand.pm
    version: 0.05
generated_by: Module::Build version 0.2604
